### ISSUE TITLE
skip unfurl plugin?

### ISSUE THREAD

**Issue by dancohen21** [obsidianforensics/hindsight#129]
seems to be running a very long time "running 'Unfurl' plugin.
Is it possible to exclude this from the analysis run from the command line?

**Comment by obsidianforensics** [comment]
No, there isn't a way to disable plugins from the command line (there is in the web UI). That would be a good feature though; I'll have to think out how to implement it. 

It's not great, but if you are running the Python version (not the compiled .exe) and want a quick way to disable the unfurl plugin, after installing hindsight, uninstall `dfir-unfurl`. hindsight.py will still try to run the unfurl plugin and it will fail, but it shouldn't impact anything else and hindsight should work fine.

**Comment by obsidianforensics** [comment]
I've removed the Unfurl plugin from the latest release, as it is taking _way_ too long. I'm planning on taking a look at why that is any trying to address, but not sure when I'll get to it.
