### ISSUE TITLE
Opening Spreadsheet Causing Error with MS Excel 2021

### ISSUE THREAD

**Issue by Mkel2010** [obsidianforensics/hindsight#135]
First install of Hindsight. I used the GUI interface to analyze some Chrome Records, which completed without error. I saved the output to an Excel spreadsheet. On opening the spreadsheet, I received a popup indicating there were issues with the spreadsheet and asking to repair them. I allowed the repair and am able to open the spreadsheet and the data looks fine. 

This is the text of the log file generated in MS Excel 2021 after the repair:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error185480_01.xml</logFileName><summary>Errors were detected in file 'I:\Reports\Item 019-007\Chrome Analysis\Hindsight Report (2022-11-13T11-44-10) Test.xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: String properties from /xl/sharedStrings.xml part (Strings)</repairedRecord></repairedRecords></recoveryLog>

**Comment by obsidianforensics** [comment]
Thanks for the report. I've had similar errors, and as far as I can tell it (at least in my case) it comes from some websites storing invalid Unicode in local Storage (some compression algos do this, like LZ-string). Python, Hindsight, and xlsxwriter can write these just fine, but Excel sees them as invalid. 

I'm not sure what to do here - altering the values so Excel can display them seems bad, as then one couldn't rely on the values as the original, but having the Excel error pop up also isn't great. If you can isolate a different cause of the issue, I'd be happy to take a look and see if I can fix it in a different way.
