### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Lou511** [obsidianforensics/hindsight#137]
I tried to use Hindsight against an iOS dataset (iOS version 16.1.1).  I received the following traceback error:

Traceback (most recent call last):
  File "bottle.py", line 868, in _handle
  File "bottle.py", line 1748, in wrapper
  File "hindsight_gui.py", line 170, in do_run
  File "pyhindsight\analysis.py", line 529, in run
  File "pyhindsight\browsers\chrome.py", line 2290, in process
  File "pyhindsight\browsers\chrome.py", line 303, in get_history
IndexError: list index out of range

Can you please help me with this issue?  Thanks Ryan!

**Comment by obsidianforensics** [comment]
Hey there - do you have some data that causes this issue that I can look at? I don't have an iOS 16 dataset.

**Comment by Lou511** [comment]
Hi Ryan, 

I do have a dataset.  Can I send you a download link?

**Comment by obsidianforensics** [comment]
Awesome, yes. Send the link to ryan@dfir.blog and I'll take a look.

**Comment by Lou511** [comment]
Sent.  Should say ***@***.*** / Citrix sharefile

**Comment by obsidianforensics** [comment]
Thanks for reporting and providing the data (it made it easy to pinpoint what went wrong). The fix is in master, I'll work on getting a new release out in the next few days after I add in a few more things I've been working on.

**Comment by Lou511** [comment]
Great to hear!  Could I ask that you discard the data once you are done
with it?

I look forward to seeing the release.  Using the results in my casework.
Nothing tells a story like Hindsight’s timeline (Excel) format.

Thanks again!

Luis

**Comment by obsidianforensics** [comment]
Yep, no problem, I'll delete it. Glad Hindsight is helpful for you :)
