### ISSUE TITLE
"no such table: downloads"

### ISSUE THREAD

**Issue by mseiden** [obsidianforensics/hindsight#159]
this is a new install of hindsight 2023.03 against chrome, detected version 89-111.
both the gui version and the command line version fail at 
line 482 in get_downloads with
"no such table: downloads"

(it created a bunch of sqllite dbs in the temp directory for cookies, history, login data, web data.)
i'm not spotting where this table is created, on a quick glance. (i wish i had time to debug further, but
it's 3am and i'm jet lagged.)

**Comment by obsidianforensics** [comment]
Hey there, and sorry for the delay. From your report, my guess is that the `History` SQLite file for some reason doesn't have the table `downloads` in it (which is strange). I'm not entirely sure what could cause the Chrome files to be in that state, but regardless it shouldn't cause Hindsight to crash. I've added some exception handing to ensure that doesn't happen in the future - thanks for the report!
