### ISSUE TITLE
ccl_chrome_indexeddb version outdated

### ISSUE THREAD

**Issue by cclgroupltd** [obsidianforensics/hindsight#168]
Hi Ryan, just pinging you to make you aware that there have been a number of enhancements and fixes in https://github.com/cclgroupltd/ccl_chrome_indexeddb that you may want to incorporate - modern indexeddbs for some sites might be failing to be read without this new version.

For the most part you shouldn't need to do anything but update the lib, but one thing that you might need to change to get the most/best data back is passing the ".blob" folder into the indexeddb constructor as records can be stored in there as well as in the leveldb itself.

**Comment by obsidianforensics** [comment]
Thanks for all your hard work on the library; it's incredibly helpful! I'll work on getting it updated here.

**Comment by obsidianforensics** [comment]
Updated in #173
