### ISSUE TITLE
Android parsing - error re: cache

### ISSUE THREAD

**Issue by LM511** [obsidianforensics/hindsight#19]
Hi Ryan.  I just tried to use Hindsight to parse Chrome (Android).  I received the following error:

Traceback (most recent call last):
  File "site-packages\bottle.py", line 862, in _handle
  File "site-packages\bottle.py", line 1732, in wrapper
  File "hindsight_gui.py", line 163, in do_run
  File "pyhindsight\analysis.py", line 129, in run
  File "pyhindsight\browsers\chrome.py", line 1721, in process
  File "pyhindsight\browsers\chrome.py", line 1312, in get_cache
UnboundLocalError: local variable 'cacheBlock' referenced before assignment

The full path I had to use was: [parent dir]\com.android.chrome\app_chrome\Default

I could not use: [parent dir]\com.android.chrome\app_chrome\ (this is what is suggested when I run from the GUI.  When I use this path, I don't get any error whatsoever.  I only get 0 results.

Am I doing something wrong?  This isn't the first time I've receive this message.  I received a similar message attempting to parse chrome from another Android.  

Please let me know what I can do to help.

Thank you.

**Comment by obsidianforensics** [comment]
Hi there,

Thanks for reporting the issue. I actually don't have an Android device and haven't personally use Hindsight again data extracted from it. That first path you mentioned (ending in 'Default') looks correct; I will change the GUI suggestion (thanks!). 

It doesn't look like you are doing anything wrong. I have been seeing some other reports of issues when parsing the cache, but I haven't been able to reproduce them. Would it be possible to send me a dataset that causes this error? If not the whole Chrome profile, even just the Cache directory would help. If so, my email is ryan@obsidianforensics.com.

Thanks,
Ryan

**Comment by obsidianforensics** [comment]
I've added error handling around this so it shouldn't crash anymore at least. I'm working on redoing this whole section of code as part of moving to Python 3.

If do you have any Android Chrome cache data that you can share, I'd still love to get my hands on it and make sure Hindsight can parse it. Thanks!
