### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by grayfold3d** [obsidianforensics/hindsight#22]
Would it be possible to have Hindsight recursively search a given path and parse each profile? For example
ideally something like this would work so it would grab each Windows profile and then also if there are multiple Chrome user profiles it would parse them too

hindsight.exe -i C:\ -o test_run
hindsight.exe -i C:\Users -o test_run

**Comment by obsidianforensics** [comment]
Thanks for the request! I've added this in in the new release (v2.3).
