### ISSUE TITLE
Possible for hindsight to find chrome profiles from root folder?

### ISSUE THREAD

**Issue by EricZimmerman** [obsidianforensics/hindsight#24]
For example, given a starting point of 

C:\Temp\tout

where there exists profiles like this:

C:\Temp\tout\C\Users\e\AppData\Local\Google\Chrome\User Data\Default

can you change hindsight to discover the profiles that exist, vs me having to manually specify and know what profiles exist?

we have a module for KAPE that uses hindsight but it requires me to run it against the second dir vs the first, so its not ideal.

would be nice to point hindsight to a dir and have it tell me whats there, maybe via a -r switch or something?

**Comment by obsidianforensics** [comment]
I'll take another look at this - the philosophy so far has been for Hindsight to focus **only** on the parsing, while relying on the user to do the mounting of any evidence files, locating the Chrome profile directory, etc. 

I can see this being very helpful from a user-experience perspective though, so I'll try and build in a search-type function. Thanks for the issue.

**Comment by EricZimmerman** [comment]
perhaps if you look for the Users or Documents and settings folder recursively based on the parameter you are given for -r, then deal with each profile folder, i think that would work and people would love it! 

thanks for looking at this

**Comment by obsidianforensics** [comment]
Added in v2.3. It uses the same -i switch as before, it just searches that path now. Pointing -i to C:\Temp\tout in your example should behave like you want.
