### ISSUE TITLE
Make a temp copy of locked databases

### ISSUE THREAD

**Issue by obsidianforensics** [obsidianforensics/hindsight#28]
Hindsight can't open SQLite dbs that are locked and in use. It should be feasible to make a temp copy of the locked database and use that instead. The same logic might apply to LevelDB directories, but I need to investigate more.

**Comment by sank8dalvi** [comment]
@obsidianforensics  I have added a similar feature in History Analyzer project for Chrome. Here's the link of the issue: https://github.com/karthikeyankc/HistoryAnalyzer/issues/1
If you can assign me this issue then I will investigate more on doing the same for this project and will create a PR for the same.

I am ready to be assigned to solve this issue.

**Comment by obsidianforensics** [comment]
Thanks! I've assigned the issue to you. Feel free to ask any questions if needed.

**Comment by sank8dalvi** [comment]
Sure!
Can you let me know which version of python 3 are you using with this project? Should I go ahead with python 3.8?

**Comment by sank8dalvi** [comment]
Hey @obsidianforensics 
I am getting `plyvel._plyvel.CorruptionError: b'Corruption: corrupted compressed block contents'`  while reading leveldb files. I think there's some issue with plyvel v1.2 on Windows platform. I am not able to build it.
Should I create the PR only for sqlite3 databases?

**Comment by obsidianforensics** [comment]
Yes, there is a problem with plyvel on Windows; I also have not been able to get it to build. It does work on linux, so the leveldb parsers work there fine. If you want to keep the PR for SQLite only, that's fine; if you want to do it for leveldb as well, folks running linux would benefit. Either way I fine; I appreciate the help.

**Comment by sank8dalvi** [comment]
#49 I have added the feature to read SQLite DBs when they are locked by creating the local copies and deleting them after processing.
