### ISSUE TITLE
line 224 error

### ISSUE THREAD

**Issue by itripc** [obsidianforensics/hindsight#32]
could be simple human error but I try to run the -i    and -o  option and I continue to get   error line 224 except ImportError, e:

**Comment by obsidianforensics** [comment]
Hi, thanks for the bug report. Can you give me a little more info around the issue? 

- What version of Hindsight are you running?
- What OS? If Windows, exe or .py version of Hindsight?
- What's the full command line you are using?
- When you get "error line 224 except ImportError, e:" is that in the log, or does Hindsight crash with that?
- Can you attached the hindsight.log file (or a snippet of it)?
- That line number makes me think it's a problem loading the plugins. Does all the parsing work as expected before that?

Thanks!

**Comment by itripc** [comment]
Apologies I just noticed the response. I tried with home pc the gui and got another error,  Windows 10 Build 17134.829, i used the Windows gui exe

![image](https://user-images.githubusercontent.com/31646277/59896215-23686d80-9394-11e9-8bee-0aba061e6ab6.png)


Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [20/Jun/2019 18:56:46] "GET / HTTP/1.1" 200 18737
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/styles.css HTTP/1.1" 200 5533
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/github.png HTTP/1.1" 200 1571
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/fonts/OpenSans-Regular.woff2 HTTP/1.1" 200 47016
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/fonts/OpenSans-Light.woff2 HTTP/1.1" 200 45900
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/slack.png HTTP/1.1" 200 7645
127.0.0.1 - - [20/Jun/2019 18:56:46] "GET /static/twitter.png HTTP/1.1" 200 6650
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/h.png HTTP/1.1" 200 500313
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/chrome_logo.svg HTTP/1.1" 200 6245
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/error.png HTTP/1.1" 200 322
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/brave_logo.png HTTP/1.1" 200 29951
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/icons/manifest.json HTTP/1.1" 200 760
127.0.0.1 - - [20/Jun/2019 18:56:47] "GET /static/icons/favicon-32x32.png HTTP/1.1" 200 2490

    Profile: E:\home_test_labs\chrome_browser\Default
                     Detected Chrome version:            [     73 ]
                                 URL records:            [  15086 ]
                            Download records:            [    372 ]
                              Cookie records:            [    151 ]
                            Autofill records:            [   1839 ]
                            Bookmark records:            [ Failed ]
Traceback (most recent call last):
  File "site-packages\bottle.py", line 862, in _handle
  File "site-packages\bottle.py", line 1732, in wrapper
  File "hindsight_gui.py", line 163, in do_run
  File "pyhindsight\analysis.py", line 207, in run
  File "pyhindsight\browsers\chrome.py", line 1847, in process
  File "pyhindsight\browsers\chrome.py", line 721, in get_local_storage
  File "pyhindsight\browsers\chrome.py", line 1511, in get_prefixed_leveldb_pairs
LevelDBError: Corruption: error in middle of record
127.0.0.1 - - [20/Jun/2019 19:00:45] "POST /run HTTP/1.1" 500 1511
127.0.0.1 - - [20/Jun/2019 19:00:45] "GET /favicon.ico HTTP/1.1" 404 742
127.0.0.1 - - [20/Jun/2019 19:02:35] "GET /static/icons/manifest.json HTTP/1.1" 304 0

    Profile: E:\home_test_labs\chrome_browser\Default
                     Detected Chrome version:            [     73 ]
                                 URL records:            [  15086 ]
                            Download records:            [    372 ]
                              Cookie records:            [    151 ]
                            Autofill records:            [   1839 ]
                            Bookmark records:            [ Failed ]
Traceback (most recent call last):
  File "site-packages\bottle.py", line 862, in _handle
  File "site-packages\bottle.py", line 1732, in wrapper
  File "hindsight_gui.py", line 163, in do_run
  File "pyhindsight\analysis.py", line 207, in run
  File "pyhindsight\browsers\chrome.py", line 1847, in process
  File "pyhindsight\browsers\chrome.py", line 721, in get_local_storage
  File "pyhindsight\browsers\chrome.py", line 1511, in get_prefixed_leveldb_pairs
LevelDBError: Corruption: error in middle of record
127.0.0.1 - - [20/Jun/2019 19:02:36] "POST /run HTTP/1.1" 500 1511

**Comment by HsunGong** [comment]
> could be simple human error but I try to run the -i and -o option and I continue to get error line 224 except ImportError, e:

use `except ImportError as e:` to fix this in python3

**Comment by obsidianforensics** [comment]
I've put more error handling around LevelDB corruption (https://github.com/obsidianforensics/hindsight/commit/a479d9da05559baaa65c5650057c629484d823ec), so this should work better now. If you rerun with the latest version and still see errors, please let me know.
