### ISSUE TITLE
sqlite text_factory

### ISSUE THREAD

**Issue by trajber** [obsidianforensics/hindsight#4]
Traceback (most recent call last):
  File "hindsight.py", line 1919, in <module>
    main()
  File "hindsight.py", line 1913, in main
    write_sqlite(target_browser)
  File "hindsight.py", line 1731, in write_sqlite
    item.interpretation))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by obsidianforensics** [comment]
Hello,
I've made some changes to the way Hindsight stores data internally; can you try running this again and let me know if the new changes fixed this?

**Comment by trajber** [comment]
Now I got a different error:

 Writing "Hindsight Internet History Analysis (2015-07-14T14-01-25).sqlite"
Traceback (most recent call last):
  File "hindsight.py", line 1941, in <module>
    main()
  File "hindsight.py", line 1935, in main
    write_sqlite(target_browser)
  File "hindsight.py", line 1764, in write_sqlite
    (extension.name, extension.description, extension.version, extension.app_id))
AttributeError: 'str' object has no attribute 'name'

**Comment by obsidianforensics** [comment]
Thanks for reporting this - should be fixed now.
