### ISSUE TITLE
PermissionError and TypeError when Hindsight encounters an inaccessible directory

### ISSUE THREAD

**Issue by pakonet** [obsidianforensics/hindsight#45]
When Hindsight scans a directory with subdirectories inaccessible due to NTFS permissions, it aborts with an error. There is no easy way to circumvent this on my side, as the partition is mounted as read only. Perhaps it would be better to log an error, but continue processing other subdirectories?

This is related to the improvement made in #24 (suggested by @EricZimmerman) and #34.

**Screenshots or Console Output**
```
[9868] Failed to execute script hindsight
Traceback (most recent call last):
  File "pyhindsight\analysis.py", line 365, in search_subdirs
PermissionError: [WinError 5] Access is denied: 'M:\\Users\\All Users\\Application Data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hindsight.py", line 327, in <module>
  File "hindsight.py", line 203, in main
  File "pyhindsight\analysis.py", line 393, in find_browser_profiles
  File "pyhindsight\analysis.py", line 376, in search_subdirs
  File "pyhindsight\analysis.py", line 376, in search_subdirs
  File "pyhindsight\analysis.py", line 368, in search_subdirs
TypeError: unsupported format string passed to PermissionError.__format__
```

**To Reproduce**
Set --input to a directory that contains subdirectories that cannot be accessed due to NTFS permissions. In the example above, hindsight was started with --input M:\Users.

**System Details**
 - Windows 10
 - Method of Running Hindsight: hindsight.exe (both with elevated privileges and as a regular user)
 - Hindsight version: 20200607

**Comment by pakonet** [comment]
On a side note, perhaps you could consider using os.walk() to scan the directory tree. A very simple example would be:

```
class ChromiumProfileFinder:
    def __init__(self, logger: Logger):
        self.logger = logger

    def walk_error_handler(self, e: Exception) -> None:
        self.logger.warning(str(e))

    def find_chromium_profiles(self, root_path: Path) -> Generator[str, None, None]:
        for dir, subdirectories, files in os.walk(root_path, onerror=self.walk_error_handler, followlinks=False):
            for file_name in files:
                if file_name == "History":
                    yield dir
```

(I used a generator, but you could build a list instead.)

**Comment by obsidianforensics** [comment]
@pakonet, thanks for filing this issue (so sorry it took so long to get to!) 
This should fix the reported issue - I ran it against multiple scenarios involving directories without read permissions.
