### ISSUE TITLE
ascii error writing xlsx

### ISSUE THREAD

**Issue by pittjl** [obsidianforensics/hindsight#5]
Yosemite 10.10.3
Python 2.7.10 (installed via brew, also using a virtualenv for hindsight)

Running hindsight gives an ascii error when writing the xlsx file. If I change the output format to json, all is well.

python hindsight.py -i '/Users/infosec/Library/Application Support/Google/Chrome/Default' -o test2
Couldn't import module 'win32crypt'; cookie decryption on Windows disabled.

 Hindsight v1.4.5
       Start time: 2015-06-19 08:03:31.687
  Input directory: /Users/infosec/Library/Application Support/Google/Chrome/Default
      Output name: test2

 Processing:
                     Detected Chrome version:            [     42 ]
                                 URL records:            [  21298 ]
                            Download records:            [    441 ]
                              Cookie records:            [   4974 ]
                            Autofill records:            [   1554 ]
                            Bookmark records:            [   1132 ]
                       Local Storage records:            [  24290 ]
                                  Extensions:            [     14 ]
                          Login Data records:            [     11 ]
                            Preference Items:            [     20 ]

 Running plugins:
          Chrome Extension Names (v20150125):   - 8 extension URLs parsed -
       Generic Timestamp Decoder (v20140816):     - 99 timestamps parsed -
  Google Analytics Cookie Parser (v20140813):      - 154 cookies parsed -
                 Google Searches (v20150222):     - 1423 searches parsed -
         Quantcast Cookie Parser (v20140813):      - 14 cookies parsed -
             Query String Parser (v20150222):  - 5282 query strings parsed -
         Time Discrepancy Finder (v20141214):    - 73 differences parsed -

 Writing "test2.xlsx"
Traceback (most recent call last):
  File "hindsight.py", line 1920, in <module>
    main()
  File "hindsight.py", line 1901, in main
    write_excel(target_browser)
  File "hindsight.py", line 1652, in write_excel
    workbook.close()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/workbook.py", line 295, in close
    self._store_workbook()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/workbook.py", line 518, in _store_workbook
    xml_files = packager._create_package()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/packager.py", line 140, in _create_package
    self._write_shared_strings_file()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/packager.py", line 280, in _write_shared_strings_file
    sst._assemble_xml_file()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 53, in _assemble_xml_file
    self._write_sst_strings()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 83, in _write_sst_strings
    self._write_si(string)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 110, in _write_si
    self._xml_si_element(string, attributes)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/xmlwriter.py", line 122, in _xml_si_element
    self.fh.write("""<si><t%s>%s</t></si>""" % (attr, string))
  File "/Users/Infosec/envs/hindsight/lib/python2.7/codecs.py", line 694, in write
    return self.writer.write(data)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/codecs.py", line 357, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 64: ordinal not in range(128)

**Comment by obsidianforensics** [comment]
I made a fix that I think will fix this issue.  As a last resort, Hindsight was trying to decrypt everything as if it were encrypted on Linux.  This caused "decrypted" data from Mac systems to be invalid characters and caused problems in xlsxwriter.

Please let me know if this fixed your issue.

**Comment by pittjl** [comment]
It appears I continue to have the issue. json output does still work. Also, I tried the sqlite output, and got an error that might be related:

python hindsight.py -i '/Users/Infosec/Library/Application Support/Google/Chrome/Default' -o test -f sqlite
Couldn't import module 'win32crypt'; cookie decryption on Windows disabled.


 Hindsight v1.4.6
       Start time: 2015-06-23 07:26:23.785
  Input directory: /Users/Infosec/Library/Application Support/Google/Chrome/Default
      Output name: test

 Processing:
                     Detected Chrome version:            [     42 ]
                                 URL records:            [  20980 ]
                            Download records:            [    449 ]
                              Cookie records:            [   4872 ]
                            Autofill records:            [   1554 ]
                            Bookmark records:            [   1132 ]
                       Local Storage records:            [  24299 ]
                                  Extensions:            [     13 ]
                          Login Data records:            [     11 ]
                            Preference Items:            [     20 ]

 Running plugins:
          Chrome Extension Names (v20150125):   - 11 extension URLs parsed -
       Generic Timestamp Decoder (v20140816):     - 96 timestamps parsed -
  Google Analytics Cookie Parser (v20140813):      - 153 cookies parsed -
                 Google Searches (v20150222):     - 1418 searches parsed -
         Quantcast Cookie Parser (v20140813):      - 14 cookies parsed -
             Query String Parser (v20150222):  - 5315 query strings parsed -
         Time Discrepancy Finder (v20141214):    - 79 differences parsed -

 Writing "test.sqlite"
Traceback (most recent call last):
  File "hindsight.py", line 1929, in <module>
    main()
  File "hindsight.py", line 1923, in main
    write_sqlite(target_browser)
  File "hindsight.py", line 1741, in write_sqlite
    item.interpretation))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by obsidianforensics** [comment]
I made a bunch of changes, converting str to unicode where ever I could.  Hindsight should be converting everything to Unicode as soon as it can.  I hope this fixes your problem; if not, would you be willing to provide me with some of the troublesome raw data?

**Comment by pittjl** [comment]
It appears that there is a similar problem now, but earlier in the processing chain. Instead of failing at the xlsx export, if fails at processing cookies. This occurs with xlsx and json output selected now. 

Unfortunately I cannot share the whole data set, but if there's a way to determine which record(s) are causing issues, I can share those. 

 Hindsight v1.4.6
       Start time: 2015-06-29 08:23:00.407
  Input directory: /Users/Infosec/Library/Application Support/Google/Chrome/Default
      Output name: ~/code/testing

 Processing:
                     Detected Chrome version:            [     42 ]
                                 URL records:            [  20530 ]
                            Download records:            [    455 ]
Traceback (most recent call last):
  File "hindsight.py", line 1931, in <module>
    main()
  File "hindsight.py", line 1855, in main
    target_browser.get_cookies(args.input, 'Cookies', target_browser.version)
  File "hindsight.py", line 514, in get_cookies
    cookie_value = decrypt_cookie(row.get('encrypted_value')).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 57: ordinal not in range(128)

**Comment by obsidianforensics** [comment]
I made a slight change to the Mac decryption piece and also disabled it by default.  Now you can use --decrypt [mac|linux] to try to decrypt either of those.  I need to get my hands on a Mac for a few days to try and work out the decryption kinks; in the meantime, I hope running Hindsight without '--decrypt mac' will give you some results at least.

**Comment by pittjl** [comment]
Thanks for your work on this! There's a shedload of data in this profile, and its probably not representative of what a normal profile would be. I'm not surprised at all that there are unicode problems. 

Running without "decrypt" did work as expected. Running with "decrypt" I did not get the new error above in cookies, I got an error in the xlsx module again. JSON output worked. 

 Hindsight v1.4.7
       Start time: 2015-07-01 08:18:08.413
  Input directory: /Users/Infosec/Library/Application Support/Google/Chrome/Default/
      Output name: ../newnewtest

 Processing:
                     Detected Chrome version:            [     42 ]
                                 URL records:            [  21564 ]
                            Download records:            [    471 ]
                              Cookie records:            [   4901 ]
                            Autofill records:            [   1554 ]
                            Bookmark records:            [   1132 ]
                       Local Storage records:            [  24429 ]
                                  Extensions:            [     13 ]
                          Login Data records:            [     11 ]
                            Preference Items:            [     22 ]

 Running plugins:
          Chrome Extension Names (v20150125):   - 14 extension URLs parsed -
       Generic Timestamp Decoder (v20140816):   - 22053 timestamps parsed -
  Google Analytics Cookie Parser (v20140813):       - 0 cookies parsed -
                 Google Searches (v20150222):     - 1449 searches parsed -
         Quantcast Cookie Parser (v20140813):       - 0 cookies parsed -
             Query String Parser (v20150222):  - 5201 query strings parsed -
         Time Discrepancy Finder (v20141214):     - 0 differences parsed -

 Writing "../newnewtest.xlsx"

 Finish time:  2015-07-01 08:18:41.383

python hindsight.py -i "/Users/Infosec/Library/Application Support/Google/Chrome/Default/" -o "../newnewnewtest" -t xlsx --decrypt mac
Couldn't import module 'win32crypt'; cookie decryption on Windows disabled.

Couldn't understand timezone; using UTC.

 Hindsight v1.4.7
       Start time: 2015-07-01 09:06:15.419
  Input directory: /Users/Infosec/Library/Application Support/Google/Chrome/Default/
      Output name: ../newnewnewtest

 Processing:
                     Detected Chrome version:            [     42 ]
                                 URL records:            [  21564 ]
                            Download records:            [    471 ]
                              Cookie records:            [   4901 ]
                            Autofill records:            [   1554 ]
                            Bookmark records:            [   1132 ]
                       Local Storage records:            [  24429 ]
                                  Extensions:            [     13 ]
                          Login Data records:            [     11 ]
                            Preference Items:            [     22 ]

 Running plugins:
          Chrome Extension Names (v20150125):   - 14 extension URLs parsed -
       Generic Timestamp Decoder (v20140816):   - 22152 timestamps parsed -
  Google Analytics Cookie Parser (v20140813):      - 154 cookies parsed -
                 Google Searches (v20150222):     - 1449 searches parsed -
         Quantcast Cookie Parser (v20140813):      - 14 cookies parsed -
             Query String Parser (v20150222):  - 5201 query strings parsed -
         Time Discrepancy Finder (v20141214):    - 84 differences parsed -

 Writing "../newnewnewtest.xlsx"
Traceback (most recent call last):
  File "hindsight.py", line 1939, in <module>
    main()
  File "hindsight.py", line 1920, in main
    write_excel(target_browser)
  File "hindsight.py", line 1671, in write_excel
    workbook.close()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/workbook.py", line 295, in close
    self._store_workbook()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/workbook.py", line 518, in _store_workbook
    xml_files = packager._create_package()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/packager.py", line 140, in _create_package
    self._write_shared_strings_file()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/packager.py", line 280, in _write_shared_strings_file
    sst._assemble_xml_file()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 53, in _assemble_xml_file
    self._write_sst_strings()
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 83, in _write_sst_strings
    self._write_si(string)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/sharedstrings.py", line 110, in _write_si
    self._xml_si_element(string, attributes)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/site-packages/xlsxwriter/xmlwriter.py", line 122, in _xml_si_element
    self.fh.write("""<si><t%s>%s</t></si>""" % (attr, string))
  File "/Users/Infosec/envs/hindsight/lib/python2.7/codecs.py", line 694, in write
    return self.writer.write(data)
  File "/Users/Infosec/envs/hindsight/lib/python2.7/codecs.py", line 357, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 64: ordinal not in range(128)
