### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by mgraf444** [obsidianforensics/hindsight#94]
Anyway to have it loop through all users and output them to one xlsx file? E.g. find all chrome artifacts for C:\Users\*

**Comment by obsidianforensics** [comment]
Yes, if the directory specified by -i isn't determined to be a Chrome profile, Hindsight searches through all subdirectories and processes all Chrome profiles found. So something like:

> hindsight.py -i C:\Users 

should do what you describe. It also may pick up other browser profiles that are similar to Chrome under the hood (Brave, Edge, etc) and parse those as well.

**Comment by mgraf444** [comment]
I tried the executable version and it didnt work, is it possible the executable version listed here isn't recompiled with the latest code?

**Comment by mgraf444** [comment]
ah nvm, I was using C:\users\ and it found nothign, using C:\users worked. Thanks!
