### ISSUE TITLE
Could not import module pytz

### ISSUE THREAD

**Issue by Slowhanden** [obsidianforensics/hindsight#98]
**Describe the problem**
I'm trying to run hindsight on my Windows 10 machine. I realize that the documentation for hindsight is by far outdated, but I have installed Python 2.7 according to the documentation, but that hasn't been working for me.

I have then installed Python 3.7 and installed all components according to the documentation in hindsight, but I get a syntax error on line 27 in hindsight.py.

I get the same syntaxerror by only writing "hindsight.py" in the command line and then press Return!

Not sure how to proceed, to make hindsight work on my machine? I have used "pip.exe install pytz" to be sure to have pytz on my machine.

Is there a newer version of the documentation of hindsight?

**SyntaxError code**

![hindsight 1](https://user-images.githubusercontent.com/66358828/130203518-3502e0c6-88ef-4740-84a8-e31075f1bea3.jpg)
![hindsight 2](https://user-images.githubusercontent.com/66358828/130200719-b3dc616e-4f44-4777-a215-e71580899bfb.PNG)

**System Details**
 - Analysis System OS: Windows 10 Pro, Version 20H2
 - Method of Running Hindsight: hindsight.py using Python 3.7 on Windows
 - Hindsight version: v2021.04.26
 - Target System OS: Windows
 - Target Browser: Chrome

**Comment by obsidianforensics** [comment]
Hi there - sorry I missed seeing this issue come by. That syntax error leads me to believe that Python 2.7 was trying to run hindsight.py, which doesn't work anymore (as you discovered). Python 3.8 or later is preferred. The easiest method on Windows is to use the [compiled binaries](https://github.com/obsidianforensics/hindsight/releases/latest). 

I will work on updating the docs, and at a minimum remove that (very) outdated user guide.
